## Database Properties
spring.datasource.url=jdbc:postgresql://xxxxxx/xxxxxx
spring.datasource.username=xxxxxx
spring.datasource.password=xxxxx
spring.datasource.driver-class-name=org.postgresql.Driver

## Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

